---
title: "Dee and Wycoff (2015) RD Exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(ggplot2)
```



```{r Dee and Wycoff, echo=FALSE}

results <- list()
pvals <- list()
full_results <- list()
full_pvals <- list()
plots <- list()
fits <- list()
full_fits <- list()
band_results <- list()
band_pvals <- list()

outcome <- 'retain_yr_2'

iters <- 10000

for (i in 1:iters) {

  N <- 2000 # number of teachers (roughly what's in the paper, per year)
  mu1 <- 0 # year 1 mean
  mu2 <- 0 # year 2 mean
  rho <- .35 # common year-to-year correlation in teacher value-added from https://www.brookings.edu/research/evaluating-teachers-the-important-role-of-value-added/
  
  # Generate bivariate normal data
  mu <- c(mu1,mu2) # Mean vector
  sigma <- matrix(c(1, rho, rho, 1),
             2) # Covariance matrix
  
  teacher_scores <- mvrnorm(N, mu = mu, Sigma = sigma ) 
  colnames(teacher_scores) <- c("Year 1 Score","Year 2 Score")
  
  # Create ME score cutoff indicator
  cutoff <- -1 # 16% of ME vs E sample were ME; qnorm(.16) = -1
  data <- data.frame(teacher_scores)
  data$ME_1 <- data$Year.1.Score < cutoff
  data$ME_2 <- data$Year.2.Score < cutoff
  
  # simulate retention
  theta <- .4 # relationship between retention probability and score
  base <- 1.5 # base rate of retention parameter
  data$prob_of_retention_yr1 <- 1/(1+exp(-1*(base + theta*data$Year.1.Score)))
  data$prob_of_retention_yr2 <- 1/(1+exp(-1*(base + theta*data$Year.2.Score)))
  
  data$retain_yr_1 <- rbinom(nrow(data), 1, data$prob_of_retention_yr1)
  data$retain_yr_2 <- rbinom(nrow(data), 1, data$prob_of_retention_yr2)
  
  # Check conditional retention rates
  mean(data$retain_yr_1[data$ME_1==1])
  mean(data$retain_yr_1[data$ME_1==0])
  
  #plot(density(data$Year.2.Score[data$ME_1==0]))
  
  # distance from cutoff
  data$yr2_dist <- abs(data$Year.2.Score - cutoff)
  data$Year.2.Score_centered <- data$Year.2.Score - cutoff
  
  # Create interaction to let slope vary after cutoff
  data$yr2_scoreXME_2 <- data$ME_2*data$Year.2.Score_centered
  
  # RD model
  RD_formula <- paste0(outcome, ' ~ ME_2 + Year.2.Score_centered + yr2_scoreXME_2')
  RD <- lm(RD_formula, data = subset(data, ME_1==0))
  band_RD <- lm(RD_formula, data = subset(data, ME_1==0 & yr2_dist < 1))
  RD_full <- lm(RD_formula, data = subset(data, yr2_dist < 1))
  
  if (i <= 10) {
    fits[[i]] <- RD
    full_fits[[i]] <- RD_full
  }
  
  results[[i]] <- RD$coefficients[[2]]
  pvals[[i]] <- summary(RD)$coefficients[[2,4]]
  
  band_results[[i]] <- band_RD$coefficients[[2]]
  band_pvals[[i]] <- summary(band_RD)$coefficients[[2,4]]
  
  full_results[[i]] <- RD_full$coefficients[[2]]
  full_pvals[[i]] <- summary(RD_full)$coefficients[[2,4]]
  
  data$est_ret_prob_yr2 <- predict(RD, data)
  
  if (i <= 10) {
    plots[[i]] <- ggplot(data, aes(x=Year.2.Score , y=retain_yr_2)) +
      stat_summary_bin(fun.y='mean', bins=20,
                       color='blue', size=2, geom='point') +
        geom_line(color='red', data=subset(data, ME_2==0 & ME_1==0), aes(x=Year.2.Score, y=est_ret_prob_yr2)) +
        geom_line(color='red', data=subset(data, ME_2==1 & ME_1==0), aes(x=Year.2.Score, y=est_ret_prob_yr2)) +
        geom_vline(xintercept=cutoff, color='black', linetype='dashed')
  }
}

results <- unlist(results)
pvals <- unlist(pvals)
full_results <- unlist(full_results)
full_pvals <- unlist(full_pvals)
band_results <- unlist(band_results)
band_pvals <- unlist(band_pvals)
hist(pvals)
hist(results)
hist(full_results)
hist(full_pvals)
```

```{r measurement_error version of above, echo=FALSE}
results <- list()
pvals <- list()
full_results <- list()
full_pvals <- list()
plots <- list()
fits <- list()
full_fits <- list()
band_results <- list()
band_pvals <- list()

outcome <- 'retain_yr_2'

iters <- 10000

for (i in 1:iters) {

  N <- 2000 # number of teachers (roughly what's in the paper, per year)
  true_scores <- rnorm(N, mean=0, sd=1)
  sigma <- 2 # measurement error (gets year-to-year correlation similar to 1st section)
  Year.1.error <- rnorm(N, mean=0, sd=sigma)
  Year.2.error <- rnorm(N, mean=0, sd=sigma)
  Year.3.error <- rnorm(N, mean=0, sd=sigma)
  
  data <- data.frame(true_scores=true_scores)
  data$Year.1.Score <- data$true_scores + Year.1.error
  data$Year.2.Score <- data$true_scores + Year.2.error
  data$Year.3.Score <- data$true_scores + Year.3.error
  
  # Create ME score cutoff indicator
  cutoff <- -1 # 16% of ME vs E sample were ME; qnorm(.16) = -1
  data$ME_1 <- data$Year.1.Score < cutoff
  data$ME_2 <- data$Year.2.Score < cutoff
  
  # simulate retention
  theta <- .4 # relationship between retention probability and score
  base <- 1.5 # base rate of retention parameter
  data$prob_of_retention_yr1 <- 1/(1+exp(-1*(base + theta*data$Year.1.Score)))
  data$prob_of_retention_yr2 <- 1/(1+exp(-1*(base + theta*data$Year.2.Score)))
  
  data$retain_yr_1 <- rbinom(nrow(data), 1, data$prob_of_retention_yr1)
  data$retain_yr_2 <- rbinom(nrow(data), 1, data$prob_of_retention_yr2)
  
  # Check conditional retention rates
  mean(data$retain_yr_1[data$ME_1==1])
  mean(data$retain_yr_1[data$ME_1==0])
  
  #plot(density(data$Year.2.Score[data$ME_1==0]))
  
  # distance from cutoff
  data$yr2_dist <- abs(data$Year.2.Score - cutoff)
  data$Year.2.Score_centered <- data$Year.2.Score - cutoff
  
  # Create interaction to let slope vary after cutoff
  data$yr2_scoreXME_2 <- data$ME_2*data$Year.2.Score_centered
  
  # RD model
  RD_formula <- paste0(outcome, ' ~ ME_2 + Year.2.Score_centered + yr2_scoreXME_2')
  RD <- lm(RD_formula, data = subset(data, ME_1==0))
  band_RD <- lm(RD_formula, data = subset(data, ME_1==0 & yr2_dist < 1))
  RD_full <- lm(RD_formula, data = subset(data, yr2_dist < 1))
  
  if (i <= 10) {
    fits[[i]] <- RD
    full_fits[[i]] <- RD_full
  }
  
  results[[i]] <- RD$coefficients[[2]]
  pvals[[i]] <- summary(RD)$coefficients[[2,4]]
  
  band_results[[i]] <- band_RD$coefficients[[2]]
  band_pvals[[i]] <- summary(band_RD)$coefficients[[2,4]]
  
  full_results[[i]] <- RD_full$coefficients[[2]]
  full_pvals[[i]] <- summary(RD_full)$coefficients[[2,4]]
  
  data$est_ret_prob_yr2 <- predict(RD, data)
  
  if (i <= 10) {
    plots[[i]] <- ggplot(data, aes(x=Year.2.Score , y=retain_yr_2)) +
      stat_summary_bin(fun.y='mean', bins=20,
                       color='blue', size=2, geom='point') +
        geom_line(color='red', data=subset(data, ME_2==0 & ME_1==0), aes(x=Year.2.Score, y=est_ret_prob_yr2)) +
        geom_line(color='red', data=subset(data, ME_2==1 & ME_1==0), aes(x=Year.2.Score, y=est_ret_prob_yr2)) +
        geom_vline(xintercept=cutoff, color='black', linetype='dashed')
  }
}

results <- unlist(results)
pvals <- unlist(pvals)
full_results <- unlist(full_results)
full_pvals <- unlist(full_pvals)
band_results <- unlist(band_results)
band_pvals <- unlist(band_pvals)
hist(pvals)
hist(results)
hist(full_results)
hist(full_pvals)
```

